<a href="https://colab.research.google.com/github/svenkatlata/Machine_Learning_Revision_Notes/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing NumPy

In [ ]:
import numpy as np

## Creating Arrays

In [ ]:
arr1 = np.array([1, 2, 3])                # 1D array
print("arr1:", arr1)

arr1: [1 2 3]


In [ ]:
arr2 = np.array([[1, 2], [3, 4]])        # 2D array
print("arr2:", arr2)

arr2: [[1 2]
 [3 4]]


In [ ]:
zeros = np.zeros((2, 3))                 # Array of zeros
print("zeros:", zeros)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((2, 3))                   # Array of ones
print("ones:", ones)

ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full = np.full((2, 3), 7)                # Array of a constant
print("full:", full)

full: [[7 7 7]
 [7 7 7]]


In [ ]:
identity = np.eye(3)                     # Identity matrix
print("identity:", identity)

identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
random = np.random.rand(2, 3)            # Random array
print("random:", random)

random: [[0.57410216 0.58996726 0.9621054 ]
 [0.54678423 0.32119729 0.92720906]]


In [ ]:
arange = np.arange(0, 10, 2)             # Array with range and step
print("arange:", arange)

arange: [0 2 4 6 8]


In [ ]:
linspace = np.linspace(0, 1, 5)          # Array with linearly spaced values
print("linspace:", linspace)

linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
empty = np.empty((2, 3))                 # Array with uninitialized values
print("empty:", empty)

empty: [[0.57410216 0.58996726 0.9621054 ]
 [0.54678423 0.32119729 0.92720906]]


## Array Properties

In [ ]:
shape = arr2.shape                       # Shape of the array
print("shape:", shape)

shape: (2, 2)


In [ ]:
dtype = arr1.dtype                       # Data type of the array
print("dtype:", dtype)

dtype: int64


In [ ]:
size = arr1.size                         # Number of elements in the array
print("size:", size)

size: 3


In [ ]:
ndim = arr2.ndim                         # Number of dimensions
print("ndim:", ndim)

ndim: 2


In [ ]:
itemsize = arr1.itemsize                 # Size of each element in bytes
print("itemsize:", itemsize)

itemsize: 8


In [ ]:
nbytes = arr1.nbytes                     # Total bytes consumed by the array
print("nbytes:", nbytes)

nbytes: 24


In [ ]:
strides = arr2.strides                   # Tuple of bytes to step in each dimension
print("strides:", strides)

strides: (16, 8)


## Indexing and Slicing

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("arr:", arr)

arr: [10 20 30 40 50]


In [ ]:
first_element = arr[0]                   # Accessing first element
print("first_element:", first_element)

first_element: 10


In [ ]:
slice = arr[1:4]                         # Slicing array
print("slice:", slice)

slice: [20 30 40]


In [ ]:
reversed_arr = arr[::-1]                 # Reversing array
print("reversed_arr:", reversed_arr)

reversed_arr: [50 40 30 20 10]


In [ ]:
multi_index = arr2[0, 1]                 # Access specific element in 2D array
print("multi_index:", multi_index)

multi_index: 2


In [ ]:
step_slice = arr[::2]                    # Step slicing
print("step_slice:", step_slice)

step_slice: [10 30 50]


## **Vectorization** - Basic Operations

Vectorization refers to performing operations on entire arrays (or vectors) without using explicit loops. It leverages low-level optimizations in C or Fortran for high performance.

```python
import numpy as np

# Adding two arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vectorized addition
c = a + b
print(c)  # Output: [5 7 9]
```

In [ ]:
add = arr1 + arr1                        # Element-wise addition
print("add:", add)

add: [2 4 6]


In [ ]:
subtract = arr1 - arr1                   # Element-wise subtraction
print("subtract:", subtract)

subtract: [0 0 0]


In [ ]:
multiply = arr1 * arr1                   # Element-wise multiplication
print("multiply:", multiply)

multiply: [1 4 9]


In [ ]:
divide = arr1 / arr1                     # Element-wise division
print("divide:", divide)

divide: [1. 1. 1.]


In [ ]:
dot_product = np.dot(arr1, arr1)         # Dot product
print("dot_product:", dot_product)

dot_product: 14


In [ ]:
power = np.power(arr1, 2)                # Element-wise power
print("power:", power)

power: [1 4 9]


In [ ]:
modulus = np.mod(arr1, 2)                # Element-wise modulus
print("modulus:", modulus)

modulus: [1 0 1]


In [ ]:
comparison = arr1 > 1                    # Element-wise comparison
print("comparison:", comparison)

comparison: [False  True  True]


## Mathematical Functions


In [ ]:
sqrt = np.sqrt(arr1)                     # Square root
print("sqrt:", sqrt)

sqrt: [1.         1.41421356 1.73205081]


In [ ]:
sin = np.sin(arr1)                       # Sine
print("sin:", sin)

sin: [0.84147098 0.90929743 0.14112001]


In [ ]:
cos = np.cos(arr1)                       # Cosine
print("cos:", cos)

cos: [ 0.54030231 -0.41614684 -0.9899925 ]


In [ ]:
tan = np.tan(arr1)                       # Tangent
print("tan:", tan)

tan: [ 1.55740772 -2.18503986 -0.14254654]


In [ ]:
log = np.log(arr1)                       # Natural logarithm
print("log:", log)

log: [0.         0.69314718 1.09861229]


In [ ]:
log10 = np.log10(arr1)                   # Logarithm base 10
print("log10:", log10)

log10: [0.         0.30103    0.47712125]


In [ ]:
exp = np.exp(arr1)                       # Exponential
print("exp:", exp)

exp: [ 2.71828183  7.3890561  20.08553692]


In [ ]:
abs_val = np.abs(arr1 - 2)               # Absolute value
print("abs_val:", abs_val)

abs_val: [1 0 1]


## Aggregations


In [ ]:
sum_elements = arr2.sum()                # Sum of all elements
print("sum_elements:", sum_elements)

sum_elements: 10


In [ ]:
max_element = arr2.max()                 # Maximum element
print("max_element:", max_element)

max_element: 4


In [ ]:
min_element = arr2.min()                 # Minimum element
print("min_element:", min_element)

min_element: 1


In [ ]:
mean_value = arr2.mean()                 # Mean
print("mean_value:", mean_value)

mean_value: 2.5


In [ ]:
median_value = np.median(arr2)           # Median
print("median_value:", median_value)

median_value: 2.5


In [ ]:
percentile_25 = np.percentile(arr2, 25)  # 25th Percentile
print("percentile_25:", percentile_25)

percentile_25: 1.75


In [ ]:
percentile_75 = np.percentile(arr2, 75)  # 75th Percentile
print("percentile_75:", percentile_75)

percentile_75: 3.25


In [ ]:
std_dev = arr2.std()                     # Standard deviation
print("std_dev:", std_dev)

std_dev: 1.118033988749895


In [ ]:
var = arr2.var()                         # Variance
print("var:", var)

var: 1.25


In [ ]:
cumsum = arr2.cumsum()                   # Cumulative sum
print("cumsum:", cumsum)

cumsum: [ 1  3  6 10]


In [ ]:
cumprod = arr2.cumprod()                 # Cumulative product
print("cumprod:", cumprod)

cumprod: [ 1  2  6 24]


In [ ]:
prod = arr2.prod()                       # Product of all elements
print("prod:", prod)

prod: 24


In [ ]:
argmax = arr2.argmax()                   # Index of maximum element
print("argmax:", argmax)

argmax: 3


In [ ]:
argmin = arr2.argmin()                   # Index of minimum element
print("argmin:", argmin)

argmin: 0


## Sorting


In [ ]:
sorted_arr = np.sort(arr)                # Sort array along the last axis
print("sorted_arr:", sorted_arr)

sorted_arr: [10 20 30 40 50]


In [ ]:
sorted_arr_axis0 = np.sort(arr2, axis=0) # Sort 2D array along rows
print("sorted_arr_axis0:", sorted_arr_axis0)

sorted_arr_axis0: [[1 2]
 [3 4]]


In [ ]:
sorted_arr_axis1 = np.sort(arr2, axis=1) # Sort 2D array along columns
print("sorted_arr_axis1:", sorted_arr_axis1)

sorted_arr_axis1: [[1 2]
 [3 4]]


In [ ]:
indices = np.argsort(arr)                # Indices that would sort the array
print("indices:", indices)

indices: [0 1 2 3 4]


## Reshaping and Transposing

In [ ]:
reshaped = arr1.reshape((3, 1))          # Reshaping array
print("reshaped:", reshaped)

reshaped: [[1]
 [2]
 [3]]


In [ ]:
flattened = arr2.flatten()               # Flattening array
print("flattened:", flattened)

flattened: [1 2 3 4]


In [ ]:
transposed = arr2.T                      # Transposing array
print("transposed:", transposed)

transposed: [[1 3]
 [2 4]]


In [ ]:
resize = np.resize(arr1, (2, 3))         # Resize array
print("resize:", resize)

resize: [[1 2 3]
 [1 2 3]]


In [ ]:
expand_dims = np.expand_dims(arr1, axis=0) # Add a new axis
print("expand_dims:", expand_dims)

expand_dims: [[1 2 3]]


In [ ]:
squeeze = np.squeeze(np.array([[[1]]])) # Remove axes of size 1
print("squeeze:", squeeze)

squeeze: 1


## Stacking and Splitting

In [ ]:
stacked = np.vstack((arr1, arr1))        # Vertical stacking
print("stacked:", stacked)

stacked: [[1 2 3]
 [1 2 3]]


In [ ]:
hstacked = np.hstack((arr1, arr1))       # Horizontal stacking
print("hstacked:", hstacked)

hstacked: [1 2 3 1 2 3]


In [ ]:
dstacked = np.dstack((arr1, arr1))       # Depth stacking
print("dstacked:", dstacked)

dstacked: [[[1 1]
  [2 2]
  [3 3]]]


In [ ]:
split = np.array_split(arr2, 2)          # Splitting array
print("split:", split)

split: [array([[1, 2]]), array([[3, 4]])]


In [ ]:
hsplit = np.hsplit(arr2, 2)              # Horizontal split
print("hsplit:", hsplit)

hsplit: [array([[1],
       [3]]), array([[2],
       [4]])]


In [ ]:
vsplit = np.vsplit(arr2, 2)              # Vertical split
print("vsplit:", vsplit)

vsplit: [array([[1, 2]]), array([[3, 4]])]


In [ ]:
column_stack = np.column_stack((arr1, arr1)) # Stack columns
print("column_stack:", column_stack)

column_stack: [[1 1]
 [2 2]
 [3 3]]


## Logical Operations

In [ ]:
logical_and = np.logical_and(arr1 > 1, arr1 < 3)  # Logical AND
print("logical_and:", logical_and)

logical_and: [False  True False]


In [ ]:
logical_or = np.logical_or(arr1 > 1, arr1 < 3)    # Logical OR
print("logical_or:", logical_or)

logical_or: [ True  True  True]


In [ ]:
logical_not = np.logical_not(arr1 > 2)           # Logical NOT
print("logical_not:", logical_not)

logical_not: [ True  True False]


In [ ]:
any_val = np.any(arr1 > 1)                       # Check if any value satisfies condition
print("any_val:", any_val)

any_val: True


In [ ]:
all_val = np.all(arr1 > 1)                       # Check if all values satisfy condition
print("all_val:", all_val)

all_val: False


## Masking


In [ ]:
masked = arr1[arr1 > 1]                  # Mask elements greater than 1
print("masked:", masked)

masked: [2 3]


If all the arrays are 1-D, `np.where()` is equivalent to:
```python
[xv if c else yv
 for c, xv, yv in zip(condition, x, y)]
```

In [ ]:
where = np.where(arr1 > 2, arr1, 0)      # Replace based on condition
print("where:", where)

where: [0 0 3]


In [ ]:
a = np.arange(10)
np.where(a < 5, a, 10*a)
# Output: array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
nonzero = np.nonzero(arr1)               # Indices of non-zero elements
print("nonzero:", nonzero)

nonzero: (array([0, 1, 2]),)


## Advanced Indexing


In [ ]:
index_array = arr2[[0, 1], [1, 0]]       # Select elements (0,1) and (1,0)
print("index_array:", index_array)

index_array: [2 3]


In [ ]:
boolean_indexing = arr1[arr1 % 2 == 0]   # Boolean indexing
print("boolean_indexing:", boolean_indexing)

boolean_indexing: [2]


In [ ]:
fancy_indexing = arr1[[0, 2]]            # Fancy indexing
print("fancy_indexing:", fancy_indexing)

fancy_indexing: [1 3]


In [ ]:
ix_ = np.ix_([0, 1], [0, 1])             # Create index arrays
print("ix_:", ix_)

ix_: (array([[0],
       [1]]), array([[0, 1]]))


## **Broadcasting**

Broadcasting allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array to match the larger array's shape, without physically copying the data.

### Rules:

1. Arrays are aligned from the right.
2. Dimensions are compared:
  - If they are equal, they can be operated on.
  - If one dimension is 1, it is stretched to match the other.
  - If the dimensions don't align, an error is raised.

In [ ]:
a = np.array([1, 2, 3])
b = 2  # Scalar

# Broadcasting scalar
c = a + b
print(c)  # Output: [3 4 5]

[3 4 5]


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 2, 3])

# Broadcasting
c = a + b
print(c)
# Output:
# [[ 2  4  6]
#  [ 5  7  9]]

[[2 4 6]
 [5 7 9]]


In [ ]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([1, 2, 3])

# This will raise an error
# c = a + b
# ValueError: operands could not be broadcast together with shapes (2,2) (3,)

In [ ]:
arr3 = np.array([1, 2, 3])
broadcasted = arr3 + np.array([[1], [2], [3]])
print("broadcasted:", broadcasted)

broadcasted: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
outer_product = np.outer(arr1, arr1)     # Outer product
print("outer_product:", outer_product)

outer_product: [[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
a = np.array([1, 2, 3])[:, np.newaxis]  # Reshape to (3, 1)
b = np.array([4, 5])                    # Shape (2,)

result = np.matmul(a, b[np.newaxis, :])
print(result)
# Output:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
result = a[:, np.newaxis] * b # Manual Outer Product using Broadcasting
print(result)

[[[ 4  5]]

 [[ 8 10]]

 [[12 15]]]


## Saving and Loading


In [ ]:
np.save('array.npy', arr1)               # Save to file
print("Saved arr1 to 'array.npy'")

Saved arr1 to 'array.npy'


In [ ]:
loaded_arr = np.load('array.npy')        # Load from file
print("loaded_arr:", loaded_arr)

loaded_arr: [1 2 3]


In [ ]:
np.savetxt('array.txt', arr1)            # Save as text
print("Saved arr1 to 'array.txt'")

Saved arr1 to 'array.txt'


In [ ]:
loaded_txt = np.loadtxt('array.txt')     # Load text file
print("loaded_txt:", loaded_txt)

loaded_txt: [1. 2. 3.]


In [ ]:
np.savez('arrays.npz', arr1=arr1, arr2=arr2) # Save multiple arrays
print("Saved arr1 and arr2 to 'arrays.npz'")

Saved arr1 and arr2 to 'arrays.npz'


In [ ]:
loaded_npz = np.load('arrays.npz')       # Load multiple arrays
print("loaded_npz['arr1']:", loaded_npz['arr1'], "loaded_npz['arr2']:", loaded_npz['arr2'])

loaded_npz['arr1']: [1 2 3] loaded_npz['arr2']: [[1 2]
 [3 4]]


## Linear Algebra


In [ ]:
matrix = np.array([[1, 2], [3, 4]])
print("matrix:", matrix)

matrix: [[1 2]
 [3 4]]


In [ ]:
inv_matrix = np.linalg.inv(matrix)       # Inverse
print("inv_matrix:", inv_matrix)

inv_matrix: [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
rank = np.linalg.matrix_rank(matrix)     # Rank
print("rank:", rank)

rank: 2


In [ ]:
eigvals, eigvecs = np.linalg.eig(matrix) # Eigenvalues & Eigenvectors
print("eigvals:", eigvals, "eigvecs:", eigvecs)

eigvals: [-0.37228132  5.37228132] eigvecs: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
det = np.linalg.det(matrix)              # Determinant
print("det:", det)

det: -2.0000000000000004


In [ ]:
qr = np.linalg.qr(matrix)                # QR decomposition
print("qr:", qr)

qr: QRResult(Q=array([[-0.31622777, -0.9486833 ],
       [-0.9486833 ,  0.31622777]]), R=array([[-3.16227766, -4.42718872],
       [ 0.        , -0.63245553]]))


In [ ]:
svd = np.linalg.svd(matrix)              # Singular Value Decomposition
print("svd:", svd)

svd: SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))


In [ ]:
solve = np.linalg.solve(matrix, np.array([1, 2])) # Solve linear system
print("solve:", solve)

solve: [0.  0.5]


In [ ]:
diag = np.diag(matrix)                   # Diagonal elements
print("diag:", diag)

diag: [1 4]


In [ ]:
trace = np.trace(matrix)                 # Trace of the matrix
print("trace:", trace)

trace: 5


## Random Module


In [ ]:
rand_uniform = np.random.rand(5)         # Uniform distribution
print("rand_uniform:", rand_uniform)

rand_uniform: [0.334159   0.75684354 0.96642164 0.98471765 0.60699016]


In [ ]:
rand_int = np.random.randint(0, 10, 5)   # Random integers
print("rand_int:", rand_int)

rand_int: [9 0 0 3 9]


In [ ]:
rand_normal = np.random.randn(5)         # Normal distribution
print("rand_normal:", rand_normal)

rand_normal: [-0.22194526  1.38353537  1.66899655  0.34787112 -0.60910208]


In [ ]:
rand_choice = np.random.choice(arr1, 3)  # Random choice from array
print("rand_choice:", rand_choice)

rand_choice: [3 3 2]


In [ ]:
shuffle = np.random.shuffle(arr1)        # Shuffle array in place
print("arr1 after shuffle:", arr1)

arr1 after shuffle: [1 3 2]


In [ ]:
beta_dist = np.random.beta(0.5, 0.5, 5)  # Beta distribution
print("beta_dist:", beta_dist)

beta_dist: [0.00497031 0.62959869 0.01096879 0.00352343 0.5863085 ]


In [ ]:
binomial = np.random.binomial(10, 0.5, 5)# Binomial distribution
print("binomial:", binomial)

binomial: [6 5 4 3 5]


In [ ]:
poisson = np.random.poisson(5, 5)        # Poisson distribution
print("poisson:", poisson)

poisson: [ 4 10  6  8  8]


## Tips and Tricks


In [ ]:
np.set_printoptions(precision=2)         # Set print precision
print("Set print precision to 2")

Set print precision to 2


In [ ]:
np.random.seed(42)                       # Set random seed for reproducibility
print("Set random seed to 42")

Set random seed to 42


In [ ]:
np.clip(arr1, 0, 10)                     # Clip values between 0 and 10
print("Clipped arr1 to range 0-10:", arr1)

Clipped arr1 to range 0-10: [1 3 2]


In [ ]:
np.unique(arr1)                          # Find unique elements
print("Unique elements in arr1:", np.unique(arr1))

Unique elements in arr1: [1 2 3]


In [ ]:
np.concatenate([arr1, arr1])             # Concatenate arrays
print("Concatenated arr1:", np.concatenate([arr1, arr1]))

Concatenated arr1: [1 3 2 1 3 2]


In [ ]:
np.repeat(arr1, 3)                       # Repeat elements
print("Repeated elements of arr1:", np.repeat(arr1, 3))

Repeated elements of arr1: [1 1 1 3 3 3 2 2 2]


In [ ]:
np.tile(arr1, 2)                         # Tile array
print("Tiled arr1:", np.tile(arr1, 2))

Tiled arr1: [1 3 2 1 3 2]


In [ ]:
np.histogram(arr1, bins=3)               # Histogram
print("Histogram of arr1:", np.histogram(arr1, bins=3))

Histogram of arr1: (array([1, 1, 1]), array([1.  , 1.67, 2.33, 3.  ]))
